### ISSUE TITLE
authorized question

### ISSUE THREAD

**Issue by bkyifanleo** [JasonRivers/Docker-Nagios#11]
hi 
when i run docker image with follow command 
docker run --name nagios4 -p 0.0.0.0:8080:80 jasonrivers/nagios:latest
i notice log that " Adding password for user nagiosadmin "
when i put mu linux ip:port(1.2.3.4:8080) on website user/password  required
assuming that my linux user/password like <bk/123456>
both failed when i try user/password (bk/123456 or nagiosadmin/  )
what can i do is correct?
thank you a lot ~

**Comment by JasonRivers** [comment]
The default user/pass on the image is nagiosadmin/nagios.
If you mount a volume for the nagios etc directory : 
```
-v /path-to-nagios/etc/:/opt/nagios/etc/
```
and you have a htpasswd.users in the etc directory then it will use that, if the file doesn't exist it creates one at start-up otherwise nagios won't work as you must authenticate to it by default.

If you start nagios without the htpasswd.users, once nagios has created it you can change the password for the nagiosadmin user using htpasswd from the command line of your system.

I hope this helps

Jason

**Comment by bkyifanleo** [comment]
well, it works~thx
