### ISSUE TITLE
Perl Encryption Libraries Not Present

### ISSUE THREAD

**Issue by rehashedsalt** [JasonRivers/Docker-Nagios#130]
In an attempt to use [this plugin](http://nagios.manubulon.com/snmp_storage.html) for some simple storage monitoring, I've come across an error:

```
ERROR: SNMPv3 support is unavailable (Required module Crypt/DES.pm not found). 
```

To my understanding, this doesn't actually come from my plugin, but instead the SNMP Perl module. In order for that module to work properly with SNMPv3 AuthPriv, the following packages will need to be added to the base container image:

* `libcrypt-des-perl` (even if you don't use DES privacy)
* `libdigest-hmac-perl` (it's already present, but should be noted as a known dependency)
* `libcrypt-rijndael-perl` (for AES privacy support)

Manually installing these packages while the container is live gives me my nice green boxes back.

**Comment by tronyx** [comment]
I created a fork of this repo some time ago to try and keep it up to date and resolve issues for folks: https://github.com/tronyx/Docker-Nagios

I added the two missing libs into my `:develop` tag if you would like to test it and, if everything works for you, I will merge it into master later today.

**Comment by JasonRivers** [comment]
This is very bad form to comment on every single issue within a repository to tell people to use your fork.

Unfortunately I have been busy and will sort these out, a pull request is often faster than an issue but I still have to look at them and check they are all OK and working.

I'm sorry for the delays.

**Comment by tronyx** [comment]
I meant no malice, disrespect, or ill intent by doing this. When I created the fork some time ago it seemed like your repo was dead. You then came back and did a lot of work on your repo ~7-8 months ago, but have been inactive since then. I understand we're all busy, but it seemed like the repo may have died again so I was simply trying to help folks who had reported issues see their issues resolved so that they could keep enjoying and utilizing the image.

I will refrain from publicly commenting on issues created within your repo in the future.
