### ISSUE TITLE
"{conf.d,monitor}" folder

### ISSUE THREAD

**Issue by Sudmota** [JasonRivers/Docker-Nagios#18]
First of all, thank you for this wonderful image.

I believe your line in your "latest" Dockerfile corrupts the Nagios folder /opt/nagios/etc

```
mkdir -p         ${NAGIOS_HOME}/etc/{conf.d,monitor}
```

This creates literally a folder with the name `{conf.d,monitor}`, instead of the two folders, as in the previous releases.

Naturally, my suggestion is to replace this line with two:

```
mkdir -p         ${NAGIOS_HOME}/etc/conf.d
mkdir -p         ${NAGIOS_HOME}/etc/monitor
```

Best, 
Eduardo

**Comment by JasonRivers** [comment]
Thanks for your feedback, This was a recent change by @stonio I thought I had checked it but obviously not well enough, Possibly because I externally mount the etc folder - I should stop doing that when testing!

I have reverted this, and tested without mounting etc, The next build should be good to go.

Jason.
