### ISSUE TITLE
Dumb user question

### ISSUE THREAD

**Issue by pdupreez** [JasonRivers/Docker-Nagios#30]
I cannot find anywhere how to access the UI? Any help? I am running the docker on a QNAP

**Comment by JasonRivers** [comment]
The docker container runs on port 80, if you have started it with the -p (port) flag then you can map it to whichever port you want IIRC QNAP NAS do odd things with port 80 making it inaccessible to you as a user (there's hacks, but I wouldn't bother), so if you start it with -p 8085:80/tcp then you'll be able to view the UI at http://${IP-OF-NAS}:8085 (because QNAP also use 8080 so you can't use that either)
