### ISSUE TITLE
Wrong Date

### ISSUE THREAD

**Issue by darox** [JasonRivers/Docker-Nagios#50]
Unfortunately the date is wrong under last check:, how can this be fixed?
<img width="1776" alt="wrongdate" src="https://user-images.githubusercontent.com/9934402/33528657-7a9a4a66-d864-11e7-9741-9f4712cb68cf.PNG">

**Comment by thinkitdata** [comment]
Hello, I also ran into this awhile back and while this isn't the most elegant solution it's been consistently working for me.

**From w/in your nagios container:**
In order to change timezone, remove the /etc/localtime and assign symbolic link to your desired city.

root@08ec913f43f8:/usr/share/zoneinfo# rm /etc/localtime
root@08ec913f43f8:/usr/share/zoneinfo# ln -s /usr/share/zoneinfo/America/New_York /etc/localtime
root@08ec913f43f8:/usr/share/zoneinfo# date
Thu Feb 23 08:57:53 EST 2017

Thanks for the excellent work Jason in making this image.

-Greg

**Comment by JasonRivers** [comment]
Thanks for this information @thinkitdata. Sorry for the lack of response @darox Work has been a little hectic.
I'm trying to work out how best to deal with this, IIRC the image currently uses UTC, (I could be wrong), perhaps mounting /etc/localtime from the host system is a good idea, alternatives would be to have an environment variable to set this, but this means that one must know exactly what the file is on disk, which could be an issue.

I think my preference would be mounting /etc/localtime from the host, as assuming the host time is correct, the container will also have the correct time, at the very least, the container will have the same timezone as the host in this case, which is probably the best-case-scenario.

Thanks for the kind words @thinkitdata 

@darox Please could you confirm if this is a timezone issue or if it's more than that? it would be useful to run the command "date" on both the docker host, and within the container at roughly the same time (a few seconds either way isn't an issue).

/J

**Comment by darox** [comment]
@JasonRiversThanks for responding! I run the date command and the time and date was correct om the host amd docker container.

**Comment by JasonRivers** [comment]
@darox Thanks for this, so the only thing that's wrong is nagios? I may have to look a little deeper in to this, Please could you paste a screenshot of the date command and the nagios page taken roughly at the same time?

**Comment by panov-andy** [comment]
The shortest possible way I found to fix timezone issue was Dockerfile like this:
```
FROM jasonrivers/nagios
ENV TZ=Europe/Berlin
RUN echo "SetEnv TZ $TZ" > /etc/apache2/conf-available/timezone.conf
```
PassEnv doesn't work for me.
ENV is not required, so it's possible pass Europe/Berlin directly.
Waiting for update :) 👍
