### ISSUE TITLE
Error - Could not open main config file

### ISSUE THREAD

**Issue by eliyah72** [JasonRivers/Docker-Nagios#61]
Hi Jason,
First off, thanks for all the great work.

So, the container runs with default config just fine, but when I point it to my actual config (on the VM in AWS), it gives this error message on UI:

"Error: Could not open main config file '/usr/local/nagios/etc/nagios.cfg' for reading!"

My config was pulled from a git repo and sits in usr/local/nagios/*

I started my container with this command:

docker run -d --name nagios4 
-v /usr/local/nagios/etc/:/opt/nagios/etc/ 
-v /usr/local/nagios/var/:/opt/nagios/var/ 
-p 80:80 jasonrivers/Nagios

Here’s a pattern I see in logs:

Error: Failed to process config file '/opt/nagios/etc/nagios.cfg'. Aborting
nagios: Error in configuration file '/opt/nagios/etc/nagios.cfg' - Line 453 (Check result path '/usr/local/nagios/var/spool/checkresults' is not a valid directory)

Not sure why logs still show the /opt/nagios… location, and why it can’t read the nagios.cfg. Any help will be greatly appreciated.

Thanks

**Comment by JasonRivers** [comment]
Hi,
The error is slightly odd as it references /usr/local/nagios - I'll make some assumptions, please correct me if I'm incorrect.

Your main nagios.cfg on your system is located in /usr/local/nagios/etc/nagios.cfg, But references other files or directories with the full path of /usr/local/nagios/etc/file.cfg - which of course doesn't work in the container because it's expecting the config in /opt/nagios/etc.

There's 2 things you can do here,
1) you can modify your nagios config to reference the directory in the container (/opt/nagios/etc) - you may not want to do this if you're still on the fence about using the image from what you have currently running.
2) When starting the container, you can mount /usr/local/nagios inside the container as well as /opt/nagios/etc - this way any references will work unchanged, EG:

```
docker run -d --name nagios4 \
  -v /usr/local/nagios/etc:/opt/nagios/etc    \
  -v /usr/local/nagios:/usr/local/nagios       \
  -v /usr/local/nagios/var:/opt/nagios/var    \
  -p 80:80 jasonrivers/Nagios
```

Hope this helps.

If my assumptions are incorrect, please could you show the contents of /usr/lib/nagios and /usr/lib/nagios/etc

**Comment by eliyah72** [comment]
Well, mounting /usr/local/nagios inside the container made it work like a charm, for a second I thought I'm still looking at my local nagios box lol - Many thanks Jason.
