### ISSUE TITLE
WARNING: HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by kk-taqi** [JasonRivers/Docker-Nagios#66]
Hello,

I tried this container, however every time I run with the command provided, it always stuck on the following messages. I also unable to access the web page. 

Could you please advise?

postfix/master[16]: daemon started -- version 3.1.0, configuration /etc/postfix
nagios: SERVICE ALERT: localhost;HTTP;WARNING;SOFT;1;HTTP WARNING: HTTP/1.1 401 Unauthorized - 695 bytes in 0.002 second response time
nagios: SERVICE ALERT: localhost;HTTP;WARNING;SOFT;2;HTTP WARNING: HTTP/1.1 401 Unauthorized - 695 bytes in 0.001 second response time
nagios: SERVICE ALERT: localhost;HTTP;WARNING;SOFT;2;HTTP WARNING: HTTP/1.1 401 Unauthorized - 695 bytes in 0.001 second response time
nagios: SERVICE ALERT: localhost;HTTP;WARNING;SOFT;3;HTTP WARNING: HTTP/1.1 401 Unauthorized - 695 bytes in 0.001 second

**Comment by JasonRivers** [comment]
This is simply because the default Nagios configuration for monitoring will monitor the local container only, The recommended use of this container is to mount the configuration of the services you wish to monitor in to /opt/nagios/etc instead of using the example config.

Make sure you're mapping the ports when starting the container to access the web panel, but keep in mind there is no config editor on the web panel, so you'll want to mount your own configuration in to the container either with a volume mount or a volume container to monitor the services you want.
