### ISSUE TITLE
qstat in Dockerfile

### ISSUE THREAD

**Issue by tuksi** [JasonRivers/Docker-Nagios#94]
qstat (command-line program that displays information about Internet game servers) is part of Dockerfile.

I see no reason to include it.

**Comment by JasonRivers** [comment]
That's because you don't run any game servers, I, however, do.

**Comment by tuksi** [comment]
I understand your need to have it included but it's the most pulled image on docker hub and most of the people don't need it. You still think it is required?

**Comment by JasonRivers** [comment]
Yes, I created the image for my use, it may be the most pulled image but This image was created specifically for me to use mostly with hundreds of game servers. The fact it is the most pulled image is because I am one of the only people that keep nagios up to date because it is in my interest to do so. I am happy to add features that other people require in to the image, however, removing a feature that I actively use isn't an option.
